# Generated by Django 3.2.7 on 2021-10-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20211008_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'availability',
                'verbose_name_plural': 'availabilities',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.availability'),
        ),
    ]
