# Generated by Django 3.2.7 on 2021-10-10 12:22

from django.db import migrations
import embed_video.fields
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20211010_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='trailer',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
