# Generated by Django 3.2.7 on 2021-10-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/logo.png', upload_to='products/%Y/%m/%d', verbose_name='image'),
        ),
    ]
