# Generated by Django 3.2.7 on 2021-11-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_auto_20211031_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
