# Generated by Django 3.2.7 on 2021-11-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_product_updated_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-updated_time',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
