# Generated by Django 3.2.7 on 2021-11-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_auto_20211103_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
