# Generated by Django 3.2.7 on 2021-11-11 14:11

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_zh',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='details_zh',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
