# Generated by Django 3.2.7 on 2021-11-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_auto_20211111_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_zh',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
