# Generated by Django 3.2.7 on 2021-10-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVertifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='email vertify')),
                ('email', models.EmailField(max_length=200, verbose_name='vertify email')),
                ('send_type', models.IntegerField(choices=[(1, 'register'), (2, 'forget'), (3, 'change')], verbose_name='type of vertification')),
            ],
            options={
                'verbose_name': 'Email verification code information',
                'verbose_name_plural': 'Email verification code information',
            },
        ),
    ]
